force-app/main/default/objects/Book__c/fields/Book_Type__c.field-meta.xml
<CustomField>
    <fullName>Book_Type__c</fullName>
    <label>Book Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drama</fullName>
                <default>true</default>
                <label>Drama</label>
            </value>
            <value>
                <fullName>Mediation</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Buyer_Info__c/Buyer_Info__c.object-meta.xml
<CustomObject>
    <label>Buyer Info</label>
    <nameField>
        <label>Buyer Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BuyerInfos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Buyer_Info__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drama</fullName>
                <default>true</default>
                <label>Drama</label>
            </value>
            <value>
                <fullName>Meditation</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PYID-{00000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Buyer_Info__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer Info</label>
    <referenceTo>Buyer_Info__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Price_of_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_of_Book__c</fullName>
    <label>Price of Book</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BookProvider.cls
public with sharing class BookProvider {
   
   @AuraEnabled
   public static list<Book__c> dataFeach(Buyer_Info__c dataType){
    try {
        Id id1 = UserInfo.getProfileId();
        String loggedUserName =[select id,Name from Profile where id =:id1].Name;
        system.debug('Enter the Profile Name '+loggedUserName);
if(dataType!=null && loggedUserName=='System Administrator'){

    database.insert(dataType,false);


    
return [select id,Price__c,Name,Book_Type__c from Book__c where Book_Type__c =:dataType.Interest__c];
}
else{

   return null;
    
}
        
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
   }


   @AuraEnabled
   public static string dataTableRowSlect(Payment__c dataRow){
    try {
        if(dataRow!=null){
        system.debug('enter data  ########################'+dataRow);
        Payment__c newOnj= new Payment__c();

        newOnj.Book__c=dataRow.Book__c;
        newOnj.Buyer_Info__c=dataRow.Buyer_Info__c;
        newOnj.Price_of_Book__c=dataRow.Price_of_Book__c;

        insert newOnj;


   
    return 'Row data select data in apex Payment  Done';
        

    }
    return 'Row data select data in apex Payment  Done123';
        
        
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
   }
}