force-app/main/default/objects/customerobj__c/customerobj__c.object-meta.xml
<CustomObject>
    <label>customerobj</label>
    <nameField>
        <displayFormat>CAID-{0000}</displayFormat>
        <label>customerobj Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>customerobjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_object__c/Test_object__c.object-meta.xml
<CustomObject>
    <label>Test object</label>
    <nameField>
        <displayFormat>TSID-{0000}</displayFormat>
        <label>Test object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_object__c/fields/customerobj__c.field-meta.xml
<CustomField>
    <fullName>customerobj__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>customerobj</label>
    <referenceTo>customerobj__c</referenceTo>
    <relationshipLabel>Test objects</relationshipLabel>
    <relationshipName>Test_objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerCusScenarionSixClass.cls
public class TriggerCusScenarionSixClass {
    public static void dataUpdate(list<customerobj__c>listcon,map<id,customerobj__c>newMapid){
        if(!listcon.isEmpty()){
            system.debug('List of data=='+listcon);
            list<Test_object__c>addlist=new list<Test_object__c>();
            for(customerobj__c objcus:listcon){
                if(objcus.Name__c!=newMapid.get(objcus.id).Name__c){
                    Test_object__c objtest=new Test_object__c();
                    objtest.Name__c=objcus.Name__c;
                    objtest.Description__c=objcus.Description__c;
                    addlist.add(objtest);
                }
                
                
            }
            system.debug('List of test  data=='+addlist);
          database.insert(addlist,false);  
            
        }
        
    }

}