force-app/main/default/objects/customerobj__c/customerobj__c.object-meta.xml
<CustomObject>
    <label>customerobj</label>
    <nameField>
        <displayFormat>CAID-{0000}</displayFormat>
        <label>customerobj Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>customerobjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_object__c/Test_object__c.object-meta.xml
<CustomObject>
    <label>Test object</label>
    <nameField>
        <displayFormat>TSID-{0000}</displayFormat>
        <label>Test object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_object__c/fields/customerobj__c.field-meta.xml
<CustomField>
    <fullName>customerobj__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>customerobj</label>
    <referenceTo>customerobj__c</referenceTo>
    <relationshipLabel>Test objects</relationshipLabel>
    <relationshipName>Test_objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerScenarioTenClassTest.cls
@isTest
public class TriggerScenarioTenClassTest {
    @Testsetup
    public static void insertData(){
        customerobj__c objecs=new customerobj__c();
        objecs.Name__c='kishor';
        database.insert(objecs,false);
       list<Test_object__c>addlsit=new list<Test_object__c>();
        for(integer i=1;i<5;i++){
            Test_object__c objec=new Test_object__c();
            objec.customerobj__c=objecs.id;
            addlsit.add(objec);
        }
       database.insert(addlsit,false); 
    }
    @isTest
    public static void deletData(){
        customerobj__c objecc=[select id ,Name from customerobj__c limit 1];
        database.delete(objecc,false);
        
    }

}