force-app/main/default/objects/customerobj__c/customerobj__c.object-meta.xml
<CustomObject>
    <label>customerobj</label>
    <nameField>
        <displayFormat>CAID-{0000}</displayFormat>
        <label>customerobj Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>customerobjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_object__c/Test_object__c.object-meta.xml
<CustomObject>
    <label>Test object</label>
    <nameField>
        <displayFormat>TSID-{0000}</displayFormat>
        <label>Test object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_object__c/fields/customerobj__c.field-meta.xml
<CustomField>
    <fullName>customerobj__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>customerobj</label>
    <referenceTo>customerobj__c</referenceTo>
    <relationshipLabel>Test objects</relationshipLabel>
    <relationshipName>Test_objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerScenarioTenClass.cls
public class TriggerScenarioTenClass {
    
    public static void executeData(list<customerobj__c>oldListCus){
       set<id>addset=new set<id>();
        for(customerobj__c objexs:oldListCus){
           addset.add(objexs.id);
         system.debug('Enter data  ==='+objexs.id);
        }
        list<Test_object__c>addlist=new list<Test_object__c>();
        if(!addset.isEmpty()){
            for(Test_object__c objex:[select id,Name__c,customerobj__c from Test_object__c where customerobj__c IN:addset]){
                
                addlist.add(objex);   
            }
            
        }
        
        database.delete(addlist,false);
    }

}