force-app/main/default/objects/Cricket__c/Cricket__c.object-meta.xml
<CustomObject>
    <label>Cricket</label>
    <nameField>
        <displayFormat>CKID-{0000}</displayFormat>
        <label>Cricket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>crickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cricket__c/fields/cricket_Name__c.field-meta.xml
<CustomField>
    <fullName>cricket_Name__c</fullName>
    <label>cricket Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cricket__c/fields/image__c.field-meta.xml
<CustomField>
    <fullName>image__c</fullName>
    <formula>IMAGE( Image_Url__c ,  cricket_Name__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cricket__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>West Tendines</fullName>
            </value>
            <value>
                <fullName>New Zeland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cricket__c/fields/Run__c.field-meta.xml
<CustomField>
    <fullName>Run__c</fullName>
    <label>Run</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApexClassProvider.cls
public class ApexClassProvider {
    @AuraEnabled(cacheable=true)
    public static list<Cricket__c> insertData(string Name){
        system.debug('enter the name ='+Name);
        if(Name == ''){
   return  [select id,Name,cricket_Name__c,Age__c,Nationality__c,Image_Url__c,image__c,Run__c from Cricket__c]; 
        }
        else{

       return [select id,Name,cricket_Name__c,Age__c,Nationality__c,Image_Url__c,image__c,Run__c from Cricket__c  where Nationality__c=:Name];
        } 
    }

}