force-app/main/default/objects/Caseline__c/Caseline__c.object-meta.xml
<CustomObject>
    <label>Caseline</label>
    <nameField>
        <displayFormat>CNID-{0000}</displayFormat>
        <label>Caseline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Caselines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Caseline__c/fields/Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>Installed_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installed Product</label>
    <referenceTo>Installed_Product__c</referenceTo>
    <relationshipLabel>Caselines</relationshipLabel>
    <relationshipName>Caselines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Caseline__c/fields/Sales_item_number__c.field-meta.xml
<CustomField>
    <fullName>Sales_item_number__c</fullName>
    <label>Sales item number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Installed_Product__c/Installed_Product__c.object-meta.xml
<CustomObject>
    <label>Installed Product</label>
    <nameField>
        <displayFormat>IPID-{0000}</displayFormat>
        <label>Installed Product. Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Installed_Product__c/fields/SalesOrder_number__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder_number__c</fullName>
    <label>SalesOrder number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/triggeronTaskoneAswhini.cls
public class triggeronTaskoneAswhini {
    public static void createrecord(list<Installed_Product__c>acclist){
        try{
            list<Caseline__c>addlist=new list<Caseline__c>();
            for(Installed_Product__c objistal:acclist){
                
                if(objistal.Sales_item_number__c!=null && objistal.SalesOrder_number__c!=null ){
                    Caseline__c objccse=new Caseline__c();
                    objccse.Installed_Product__c=objistal.id;
                    objccse.Sales_item_number__c=objistal.Sales_item_number__c;
                    objccse.SalesOrder_number__c=objistal.SalesOrder_number__c;
                    addlist.add(objccse);
                    
                    
                }
                
    
            }    
            
            if(!addlist.isEmpty()){
                Database.insert(addlist,false);
                
                
            }  
            
  }
       catch (Exception e) {
    // Handle the exception
    System.debug('An exception occurred: ' + e.getMessage());
}
        
    }

}