force-app/main/default/objects/DependantPicklistMdata__mdt/DependantPicklistMdata__mdt.object-meta.xml
<CustomObject>
    <label>DependantPicklistMdata</label>
    <pluralLabel>DependantPicklistMdatas</pluralLabel>
</CustomObject>

force-app/main/default/objects/DependantPicklistMdata__mdt/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mumbai</fullName>
                <default>true</default>
                <label>Mumbai</label>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Lahor</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>dhaka</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>colombo</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DependantPicklistMdata__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>China</fullName>
                <default>true</default>
                <label>China</label>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Srilanka</fullName>
            </value>
            <value>
                <fullName>Nigeria	Nigeria</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Russia	Russia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DependantPicklistMdata__mdt/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hangzhou</fullName>
                <default>true</default>
                <label>Hangzhou</label>
            </value>
            <value>
                <fullName>maharastra</fullName>
            </value>
            <value>
                <fullName>sindhu</fullName>
            </value>
            <value>
                <fullName>kotte</fullName>
            </value>
            <value>
                <fullName>NewYork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApexControllerCustomeMetaData.cls
public with sharing class ApexControllerCustomeMetaData {
    @AuraEnabled(cacheable=true)
    public static list<DependantPicklistMdata__mdt> cityData(){
        try {
            return [select id,City__c,Country__c,State__c from DependantPicklistMdata__mdt];

          
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string cityMethod(string countryName){
        try {
            return [select id,City__c,Country__c,State__c from DependantPicklistMdata__mdt where Country__c=:countryName].City__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}