force-app/main/default/objects/Amazon__c/Amazon__c.object-meta.xml
<CustomObject>
    <label>Amazon</label>
    <nameField>
        <displayFormat>AMID-{0000}</displayFormat>
        <label>Amazon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amazon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Amazon__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <formula>IMAGE( image_url__c ,  Product_Name__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Amazon__c/fields/image_url__c.field-meta.xml
<CustomField>
    <fullName>image_url__c</fullName>
    <label>image url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Amazon__c/fields/Product_detail__c.field-meta.xml
<CustomField>
    <fullName>Product_detail__c</fullName>
    <label>Product detail</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Amazon__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home and Kitchen</fullName>
            </value>
            <value>
                <fullName>Beauty</fullName>
            </value>
            <value>
                <fullName>Books</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Motorbyke</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Amazon__c/fields/Total_price__c.field-meta.xml
<CustomField>
    <fullName>Total_price__c</fullName>
    <formula>Quantites__c  *  Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AmazonClassProvider.cls
public with sharing class AmazonClassProvider {
    
    @AuraEnabled(cacheable=true)
    public static list<Amazon__c> methodName(string recordParent){
        try {
            if(string.isNotEmpty(recordParent)){
return [select id,Image__c,image_url__c,Total_price__c,Product_Name__c,Price__c,Product_detail__c,Product_Type__c from Amazon__c where Product_Type__c =: recordParent];
            }
            else{
                return [select id,Image__c,image_url__c,Total_price__c,Product_Name__c,Price__c,Product_detail__c,Product_Type__c from Amazon__c];  
            }
                  
                     
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}