force-app/main/default/objects/Leave_Managment__c/Leave_Managment__c.object-meta.xml
<CustomObject>
    <label>Leave Managment</label>
    <nameField>
        <displayFormat>LMID-{00000}</displayFormat>
        <label>Leave Managment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Managments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Managment__c/fields/From_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Date__c</fullName>
    <label>From Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Leave_Managment__c/fields/Leave_Description__c.field-meta.xml
<CustomField>
    <fullName>Leave_Description__c</fullName>
    <label>Leave Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leave_Managment__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid Leave</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement</fullName>
            </value>
            <value>
                <fullName>Paternity</fullName>
            </value>
            <value>
                <fullName>Maternity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Managment__c/fields/Name_Of_Employee__c.field-meta.xml
<CustomField>
    <fullName>Name_Of_Employee__c</fullName>
    <label>Name Of Employee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leave_Managment__c/fields/satus__c.field-meta.xml
<CustomField>
    <fullName>satus__c</fullName>
    <label>satus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>approve</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Managment__c/fields/To_Date__c.field-meta.xml
<CustomField>
    <fullName>To_Date__c</fullName>
    <label>To Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LeaveRequestController.cls
public with sharing class LeaveRequestController {
    @AuraEnabled(cacheable=true)
    public static list<Leave_Managment__c> leaveMethodS(){
        try {
          return [select id,Name_Of_Employee__c,From_Date__c,Leave_Type__c,satus__c,To_Date__c,Leave_Description__c from Leave_Managment__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
   
}